#!/usr/bin/env python3
"""
Fetch publication counts by year from OpenAlex and write _data/pubs-stats.yml.

OpenAlex is a free, public scholarly-graph API:
  https://docs.openalex.org/

The script is intentionally dependency-free (urllib only) so the GitHub
Action doesn't need a requirements file.

Run manually:
    python3 scripts/update-pubs.py
Or via the workflow at .github/workflows/update-pubs.yml.
"""

from __future__ import annotations
import datetime as dt
import json
import os
import sys
import urllib.parse
import urllib.request
from collections import Counter

# ---------------------------------------------------------------- config
AUTHOR_NAME = "Atnafu Lambebo Tonja"
# Optional: pin to a specific OpenAlex author id (e.g. "A5012345678").
# Leave None to auto-discover from the name search.
AUTHOR_OPENALEX_ID: str | None = None
# Polite-pool — OpenAlex asks you to include a contact email in the User-Agent
# or `mailto` parameter. This gets you faster, more reliable responses.
MAILTO = os.environ.get("OPENALEX_MAILTO", "atnafuatx[at]gmail[dot]com")

# Where to write the data
OUT = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "_data",
    "pubs_stats.yml",
)

API = "https://api.openalex.org"
UA = f"atnafuatx.github.io/scholar-refresh (mailto:{MAILTO})"


# ---------------------------------------------------------------- helpers
def _get(url: str) -> dict:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)


def find_author_id(name: str) -> str:
    """Pick the best author match from OpenAlex by display_name."""
    qs = urllib.parse.urlencode(
        {"search": name, "per-page": 25, "mailto": MAILTO}
    )
    data = _get(f"{API}/authors?{qs}")
    candidates = data.get("results", [])
    if not candidates:
        raise SystemExit(f"No OpenAlex author found for '{name}'")
    # Prefer the candidate whose display_name matches the query case-insensitively;
    # break ties by works_count.
    def score(a):
        return (
            a.get("display_name", "").lower() == name.lower(),
            a.get("works_count", 0),
        )
    candidates.sort(key=score, reverse=True)
    best = candidates[0]
    print(
        f"author: {best['display_name']}  "
        f"id={best['id'].split('/')[-1]}  "
        f"works={best.get('works_count', '?')}  "
        f"cites={best.get('cited_by_count', '?')}"
    )
    return best["id"].split("/")[-1]


def fetch_year_counts(author_id: str) -> dict[int, int]:
    """Return {year: count} for the author's works."""
    counts: Counter[int] = Counter()
    cursor = "*"
    while cursor:
        qs = urllib.parse.urlencode(
            {
                "filter": f"author.id:{author_id}",
                "per-page": 200,
                "cursor": cursor,
                "select": "publication_year",
                "mailto": MAILTO,
            }
        )
        data = _get(f"{API}/works?{qs}")
        for w in data.get("results", []):
            y = w.get("publication_year")
            if y:
                counts[int(y)] += 1
        cursor = data.get("meta", {}).get("next_cursor")
        if not cursor:
            break
    return dict(counts)


# ---------------------------------------------------------------- yaml writer
def write_yaml(counts: dict[int, int], author_id: str) -> None:
    today = dt.date.today().isoformat()
    lines = [
        "# Auto-generated by .github/workflows/update-pubs.yml — do NOT edit by hand.",
        "# Re-generated weekly from OpenAlex. The chart on /publications/ reads this file.",
        f"generated: \"{today}\"",
        f"source: \"openalex:{author_id}\"",
        "by_year:",
    ]
    for y in sorted(counts):
        lines.append(f"  - {{ year: {y}, count: {counts[y]} }}")
    lines.append("")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}  ({sum(counts.values())} works across {len(counts)} years)")


# ---------------------------------------------------------------- main
def main() -> int:
    author_id = AUTHOR_OPENALEX_ID or find_author_id(AUTHOR_NAME)
    counts = fetch_year_counts(author_id)
    if not counts:
        print("WARNING: 0 works returned — refusing to overwrite stats file", file=sys.stderr)
        return 1
    write_yaml(counts, author_id)
    return 0


if __name__ == "__main__":
    sys.exit(main())
